CREATE TABLE Sailors (
    sid    NUMBER(9) PRIMARY KEY,
    sname  VARCHAR(20),
    rating NUMBER(2),
    age    NUMBER(4, 2)
);

CREATE USER joe IDENTIFIED BY joe123;
CREATE USER brendan IDENTIFIED BY urboi69;

GRANT SELECT, INSERT ON Sailors TO joe;
GRANT CREATE SESSION, CREATE TABLE, ALTER, INSERT ON Sailors TO brendan WITH ADMIN OPTION;